// <auto-generated />
using System;
using FantasyRolAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FantasyRolAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230525213638_InitialMigration2")]
    partial class InitialMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FantasyRolAPI.Models.Ability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("SubclassId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubclassId");

                    b.ToTable("Ability");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Bonus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AbilityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RaceId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("bonusValue")
                        .HasColumnType("int");

                    b.Property<int>("characteristic")
                        .HasColumnType("int");

                    b.Property<int?>("setProficiency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("RaceId");

                    b.ToTable("Bonus");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Alignment")
                        .HasColumnType("int");

                    b.Property<int?>("AlignmentId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterClassId")
                        .HasColumnType("int");

                    b.Property<Guid>("CharacterClassId1")
                        .HasColumnType("char(36)");

                    b.Property<int>("CharacterRaceId")
                        .HasColumnType("int");

                    b.Property<Guid>("CharacterRaceId1")
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("int");

                    b.Property<string>("CurrentSpellSlots")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ExperiencePoints")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SubclassId")
                        .HasColumnType("int");

                    b.Property<Guid>("SubclassId1")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId1");

                    b.HasIndex("CharacterRaceId1");

                    b.HasIndex("SubclassId1");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HitDice")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("ArmoClass")
                        .HasColumnType("int");

                    b.Property<int?>("DiceType")
                        .HasColumnType("int");

                    b.Property<int?>("MinChracteristic")
                        .HasColumnType("int");

                    b.Property<int?>("Modifier")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AbilityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AgeInterval")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescAlignment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SComponents")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("School")
                        .HasColumnType("int");

                    b.Property<int>("SpellLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Spell");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Subclass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Subclass");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1990c9ee-dd88-4be3-8130-c266f5021243"),
                            Email = "rubser002@gmail.com",
                            EmailConfirmed = true,
                            Name = "ruben",
                            Password = "1234"
                        });
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Ability", b =>
                {
                    b.HasOne("FantasyRolAPI.Models.Character", null)
                        .WithMany("Abilities")
                        .HasForeignKey("CharacterId");

                    b.HasOne("FantasyRolAPI.Models.Class", null)
                        .WithMany("ClassAbilities")
                        .HasForeignKey("ClassId");

                    b.HasOne("FantasyRolAPI.Models.Subclass", null)
                        .WithMany("SubClassAbilities")
                        .HasForeignKey("SubclassId");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Bonus", b =>
                {
                    b.HasOne("FantasyRolAPI.Models.Ability", null)
                        .WithMany("Bonuses")
                        .HasForeignKey("AbilityId");

                    b.HasOne("FantasyRolAPI.Models.Race", null)
                        .WithMany("Bonuses")
                        .HasForeignKey("RaceId");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Character", b =>
                {
                    b.HasOne("FantasyRolAPI.Models.Class", "CharacterClass")
                        .WithMany()
                        .HasForeignKey("CharacterClassId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyRolAPI.Models.Race", "CharacterRace")
                        .WithMany()
                        .HasForeignKey("CharacterRaceId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyRolAPI.Models.Subclass", "Subclass")
                        .WithMany()
                        .HasForeignKey("SubclassId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");

                    b.Navigation("CharacterRace");

                    b.Navigation("Subclass");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Item", b =>
                {
                    b.HasOne("FantasyRolAPI.Models.Character", null)
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Race", b =>
                {
                    b.HasOne("FantasyRolAPI.Models.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Spell", b =>
                {
                    b.HasOne("FantasyRolAPI.Models.Character", null)
                        .WithMany("Spells")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Ability", b =>
                {
                    b.Navigation("Bonuses");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Character", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Inventory");

                    b.Navigation("Spells");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Class", b =>
                {
                    b.Navigation("ClassAbilities");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Race", b =>
                {
                    b.Navigation("Bonuses");
                });

            modelBuilder.Entity("FantasyRolAPI.Models.Subclass", b =>
                {
                    b.Navigation("SubClassAbilities");
                });
#pragma warning restore 612, 618
        }
    }
}
